// exemples/react/Image.jsx
/**
 * Un composant React de trois lignes.
 *
 * Il n'y a pas de paquet npm à installer : le script, chargé une fois dans
 * votre page, observe le DOM et prend en charge tout ce que React ajoute
 * après coup — y compris les navigations d'une application monopage.
 *
 * Ce fichier ne fait donc que donner des noms de props lisibles aux attributs.
 */
export function Image({ nom, ratio, taille, focus, immediat, alt = '', ...reste }) {
  return (
    <img
      data-dam={nom}
      data-dam-ratio={ratio}
      data-dam-taille={taille}
      data-dam-focus={focus}
      data-dam-charge={immediat ? 'immediat' : undefined}
      alt={alt}
      {...reste}
    />
  );
}

/* Utilisation :
 *
 *   <Image nom="044_32_s1" ratio="4/3" alt="Pull col roulé" />
 *   <Image nom="banniere" ratio="21/9" immediat alt="" />
 *
 * Et une seule fois, dans app/layout.jsx (Next) ou index.html (Vite) :
 *
 *   <script defer src="https://cdn.damdesk.com/damdesk.js" data-espace="votre-espace" />
 */

// exemples/vue/Image.vue
<!--
  Le même principe en Vue 3. Le script observe le DOM, donc les images
  montées par Vue sont prises en charge sans rien déclarer.
-->
<script setup>
defineProps({
  nom: { type: String, required: true },
  ratio: String,
  taille: String,
  focus: String,
  immediat: Boolean,
  alt: { type: String, default: '' },
});
</script>

<template>
  <img
    :data-dam="nom"
    :data-dam-ratio="ratio"
    :data-dam-taille="taille"
    :data-dam-focus="focus"
    :data-dam-charge="immediat ? 'immediat' : undefined"
    :alt="alt"
  >
</template>

<!--
  Utilisation :
    <Image nom="044_32_s1" ratio="4/3" alt="Pull col roulé" />

  Et dans index.html, une fois :
    <script defer src="https://cdn.damdesk.com/damdesk.js" data-espace="votre-espace"></script>
-->
